// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/en/privacy-policy": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/en/contact": {
    params: {};
  };
  "/en/profile": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/en/apps": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/apps": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/en": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
  "/en/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/en/privacy-policy" | "/privacy-policy" | "/en/contact" | "/en/profile" | "/sitemap.xml" | "/en/apps" | "/contact" | "/profile" | "/apps" | "/robots.txt" | "/en" | "/_image/*" | "/en/*" | "/*";
  };
  "routes/[en].[privacy-policy]._index.tsx": {
    id: "routes/[en].[privacy-policy]._index";
    page: "/en/privacy-policy";
  };
  "routes/[privacy-policy]._index.tsx": {
    id: "routes/[privacy-policy]._index";
    page: "/privacy-policy";
  };
  "routes/[en].[contact]._index.tsx": {
    id: "routes/[en].[contact]._index";
    page: "/en/contact";
  };
  "routes/[en].[profile]._index.tsx": {
    id: "routes/[en].[profile]._index";
    page: "/en/profile";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[en].[apps]._index.tsx": {
    id: "routes/[en].[apps]._index";
    page: "/en/apps";
  };
  "routes/[contact]._index.tsx": {
    id: "routes/[contact]._index";
    page: "/contact";
  };
  "routes/[profile]._index.tsx": {
    id: "routes/[profile]._index";
    page: "/profile";
  };
  "routes/[apps]._index.tsx": {
    id: "routes/[apps]._index";
    page: "/apps";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[en]._index.tsx": {
    id: "routes/[en]._index";
    page: "/en";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/[en].$.tsx": {
    id: "routes/[en].$";
    page: "/en/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[en].[privacy-policy]._index": typeof import("./app/routes/[en].[privacy-policy]._index.tsx");
  "routes/[privacy-policy]._index": typeof import("./app/routes/[privacy-policy]._index.tsx");
  "routes/[en].[contact]._index": typeof import("./app/routes/[en].[contact]._index.tsx");
  "routes/[en].[profile]._index": typeof import("./app/routes/[en].[profile]._index.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[en].[apps]._index": typeof import("./app/routes/[en].[apps]._index.tsx");
  "routes/[contact]._index": typeof import("./app/routes/[contact]._index.tsx");
  "routes/[profile]._index": typeof import("./app/routes/[profile]._index.tsx");
  "routes/[apps]._index": typeof import("./app/routes/[apps]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/[en]._index": typeof import("./app/routes/[en]._index.tsx");
  "routes/[_image].$": typeof import("./app/routes/[_image].$.ts");
  "routes/[en].$": typeof import("./app/routes/[en].$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};